### ISSUE TITLE
[Incompatibility] Issues with Contagion Mod 1.21  

### ISSUE THREAD

**Issue by makumaku1974** [SolipIngen/minecraft.armorrestitched#65]
The mod has somehow overwritten Contagion mod to the point. When getting an infection from basically zombies then after getting killed once by the infection. The infection kills the player instantly. I would be sure that it is this mod causing it due to mixins changed from the new update of Contagion.

**Comment by MC-Mods-Pete** [comment]
it seems to me that the Armor Restitched changes something that the onApplied method in the class StatusEffect is not called any more. My mod needs this method to work.

![Bildschirmfoto vom 2024-07-20 23-54-03](https://github.com/user-attachments/assets/e0bca08e-6ef6-4cd2-9222-97973a273aba)

**Comment by MC-Mods-Pete** [comment]
I saw a mixin for addStatusEffect in LivingEntity in the code.

The original calls effect.onApplied(...) at the end. This seems to be missing in the changed version.
![Bildschirmfoto vom 2024-07-21 00-12-56](https://github.com/user-attachments/assets/2e6c3355-f3c9-48f9-bc14-612a19a034b1)

**Comment by makumaku1974** [comment]
> I saw a mixin for addStatusEffect in LivingEntity in the code.
> 
> The original calls effect.onApplied(...) at the end. This seems to be missing in the changed version. ![Bildschirmfoto vom 2024-07-21 00-12-56](https://private-user-images.githubusercontent.com/170182225/350726259-2e6c3355-f3c9-48f9-bc14-612a19a034b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzI1NzIsIm5iZiI6MTcyMTUzMjI3MiwicGF0aCI6Ii8xNzAxODIyMjUvMzUwNzI2MjU5LTJlNmMzMzU1LWYzYzktNDhmOS1iYzE0LTYxMmExOWEwMzRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwMzI0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGNhZjVjMWRlNjFkY2MxYzQ3MTg4MTU3ZThkY2NkYjY4Yjg0ZThmMjc3MmY2NDQ0MWY1ZTA2M2RhODEyYjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EXogeXmefAZYEJ6leZnlqiw0cB7ZeygvCKqCjKv-5Ac)

what does this mean btw.

**Comment by MC-Mods-Pete** [comment]
this need to be fixed in Armor Restitched, because it breaks the API of StatusEffect (onApplied gets never called). Every mod using onApplied will be broken in combination with Armor Restitched.

**Comment by MC-Mods-Pete** [comment]
The patch below revives the onApplied method in StatusEffect

`diff --git a/src/main/java/solipingen/armorrestitched/mixin/entity/LivingEntityMixin.java b/src/main/java/solipingen/armorrestitched/mixin/entity/LivingEntityMixin.java
--- a/src/main/java/solipingen/armorrestitched/mixin/entity/LivingEntityMixin.java	(revision f87a15488425139089243e4b93f93010ae0ff898)
+++ b/src/main/java/solipingen/armorrestitched/mixin/entity/LivingEntityMixin.java	(date 1721594180701)
@@ -435,10 +435,12 @@
         if (oldStatusEffectInstance == null) {
             this.activeStatusEffects.put(statusEffectInstance.getEffectType(), statusEffectInstance);
             this.invokeOnStatusEffectApplied(statusEffectInstance, source);
+            effect.onApplied((LivingEntity)(Object) this);
             cbireturn.setReturnValue(true);
         }
         else if (oldStatusEffectInstance != null && oldStatusEffectInstance.upgrade(statusEffectInstance)) {
             this.invokeOnStatusEffectUpgraded(oldStatusEffectInstance, true, source);
+            effect.onApplied((LivingEntity)(Object) this);
             cbireturn.setReturnValue(true);
         }
         else {
`

**Comment by makumaku1974** [comment]
Ill be checking this one out.
